### ISSUE TITLE
[Suggestion] Server groups

### ISSUE THREAD

**Issue by Arkobat** [masagameplay/MaSuiteCore#22]
It could be neat to have server groups.
Currently, we have different plugins to make sure our warps only are shared on the appropriate servers, with MaSuite being the newest one to the collection.

An example config, for the individual spigot servers, could be something like this:
```yaml
# If you have a network with different groups, you can split the servers into groups here
groups:
  # Set to true to enable
  enabled: true
  # All servers with the same group tag will share same same warps, teleports, chats etc.
  serverGroup: Skyblock
```
Example group of how servers are split into groups, if the text wasn't clear enough.
![Group preview](https://cdn.discordapp.com/attachments/467118216507031562/692028478249369700/unknown.png)
